# Generated by Django 5.0.2 on 2024-03-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("established", models.CharField(max_length=200)),
                ("employees_count", models.IntegerField()),
                ("internal_professinal_service", models.BooleanField()),
                ("last_demo", models.DateTimeField()),
                ("last_review", models.DateTimeField()),
            ],
        ),
    ]
