# Generated by Django 5.0.2 on 2024-03-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="company_dispaly_picture",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
