# Generated by Django 5.0.2 on 2024-03-17 23:35

import django.core.files.storage
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_vendor_company_dispaly_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="company_background_picture",
            field=models.ImageField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(
                    location="pages/static"
                ),
                upload_to=pages.models.company_background_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company_dispaly_picture",
            field=models.ImageField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(
                    location="pages/static"
                ),
                upload_to=pages.models.company_profile_upload_path,
            ),
        ),
    ]
