# Generated by Django 5.0.2 on 2024-03-18 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_vendor_company_background_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="company_url",
            field=models.TextField(
                default="", validators=[django.core.validators.URLValidator()]
            ),
        ),
    ]
