# Generated by Django 5.0.2 on 2024-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_alter_vendor_company_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
