# Generated by Django 5.0.2 on 2024-03-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0007_vendor_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_area", models.CharField(max_length=200)),
                ("modules", models.CharField(max_length=200)),
                ("financial_services_client_types", models.CharField(max_length=200)),
                ("cloud", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="description",
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_tel_number",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "ProductCapability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.productcapability",
                    ),
                ),
            ],
        ),
    ]
