# Generated by Django 5.0.2 on 2024-03-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_location_productcapability_remove_vendor_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ProductCapability",
        ),
        migrations.AddField(
            model_name="productcapability",
            name="Product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.product",
            ),
        ),
    ]
