# Generated by Django 5.0.2 on 2024-03-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_alter_productcapability_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcapability",
            name="Product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.product",
            ),
        ),
    ]
