# Generated by Django 5.0.2 on 2024-03-18 12:47

import django.core.files.storage
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_alter_productcapability_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="",
                storage=django.core.files.storage.FileSystemStorage(
                    location="pages/static"
                ),
                upload_to=pages.models.product_image_upload_path,
            ),
        ),
    ]
