# Generated by Django 5.0.2 on 2024-03-26 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Vendor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.vendor",
            ),
        ),
    ]
