# Generated by Django 5.0.2 on 2024-03-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_product_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="last_demo",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="last_review",
            field=models.DateField(),
        ),
    ]
